# Generated by Django 4.0.3 on 2022-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursearrangement',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '理论课'), (2, '实验课')], default=1, verbose_name='课程类型'),
        ),
    ]
